# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-02 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='data_of_birth',
        ),
        migrations.AddField(
            model_name='pet',
            name='contact_person_id',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='date_of_birth',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='character',
            field=models.CharField(choices=[('calm', 'Calm'), ('friendly', 'Friendly'), ('defender', 'Defender'), ('hunter', 'Hunter'), ('playful', 'playful')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('m', 'M'), ('f', 'F')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], max_length=10),
        ),
    ]
