# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-02 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171202_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(default='media/default.jpg', upload_to='pets'),
        ),
    ]
